DEEPSORT:
  REID_CKPT: "/home/transdata/attendance_deepsort/data.pt"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 50
  N_INIT: 2
  NN_BUDGET: 100
  MATCHING_CONF: 0.4